Learning Pytorch! Thank you to Daniel Bourke for his 25 hour long course!

In [6]:
import torch
import pickle
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as pyplot

print(torch.__version__)

2.4.0+cpu


Intro to tensors

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

# Get tensor back as Python int

scalar.item()

7

In [25]:
# Testing dimensions

testten = torch.tensor([[1,2],
                        [4,5],
                        [7,8]])

# First shape number refers to outer square brackets, the second to the second outer, etc.
# Tensors cannot be jagged
testten.shape

torch.Size([3, 2])

TENSOR/MATRIX in UPPER CASE

variables and vectors in lower case

size and shape are same thing in pytorch

In [59]:
x = torch.arange(1.,10.) # Putting a dot at the end ensures the data type is float
print(x, x.dtype)
x_newdim = x.reshape(1,9)
print(x_newdim) # Notice the new bracket!
print(x.reshape(3,3)) # Reshape must have the total number of elements equal to the original.

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.float32
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [45]:
z = x.view(1,9) # Changing anything in a view of a tensor, also changes the tensor.
print(z)

z[:,0] = 5

print(z,x)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [55]:
x_stackedh = torch.stack([x,x,x,x],dim=0)
print(x_stackedh)

x_stackedv = torch.stack([x,x,x,x],dim=1)
print(x_stackedv)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [63]:
print(x_newdim.shape)

x_squeezed = torch.squeeze(x_newdim)

print(x_squeezed.shape)


torch.Size([1, 9])
torch.Size([9])


In [27]:
with open('data/event_dict.pkl', 'rb') as file:
    ev_dict = pickle.load(file)

print(ev_dict[0].keys())

event0 = torch.tensor(ev_dict[0]['data'])

event0.device

dict_keys(['mean_SNR', 'bin_time', 'data'])


device(type='cpu')